ACCOUNTS = [ "GCVDUFYCKUUC4HE7SHAKGETPDKOQH5BLUWDFXDJTFPFN62D7S4YIWIMT", "GAXK5FYWOOTD3SRXWAOB3BODZGQKZZYF7D4VKOR3LRBCNMSOGCVGA7QA" ]
SIGNING_KEY = "GCVDUFYCKUUC4HE7SHAKGETPDKOQH5BLUWDFXDJTFPFN62D7S4YIWIMT"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2022"
TRANSFER_SERVER = "https://lastasset.herokuapp.com/sep6"
TRANSFER_SERVER_SEP0024 = "https://lastasset.herokuapp.com/sep24"
WEB_AUTH_ENDPOINT = "https://lastasset.herokuapp.com/auth"
KYC_SERVER = "https://lastasset.herokuapp.com/kyc"
DIRECT_PAYMENT_SERVER = "https://lastasset.herokuapp.com/sep31"
QUOTE_SERVER = "https://lastasset.herokuapp.com/sep38"
FEDERATION_SERVER="https://lastasset.herokuapp.com/federation"
[[CURRENCIES]]
code = "LHTASSET"
issuer = "GCVDUFYCKUUC4HE7SHAKGETPDKOQH5BLUWDFXDJTFPFN62D7S4YIWIMT"
status = "test"
is_asset_anchored = false
desc = "Stellar Reference Token (SRT) is an asset issued on testnet and is used as an anchored asset for this reference server for demonstration and testing purposes."

[DOCUMENTATION]
ORG_NAME = "Stellar Development Foundation"
ORG_URL = "https://stellar.org"
ORG_DESCRIPTION = "The Stellar Development Foundation (SDF) is a non-profit organization whose mission is to create equitable access to the global financial system."
ORG_GITHUB = "stellar"